jest.config.js, www/pages/home/Home.test.js, www/pages/home/__snapshots__/Home.test.js.snap
Fixes ignore patterns, which, [as per the documentation](https://jestjs.io/docs/en/configuration.html#testpathignorepatterns-array-string), expect regex patterns.
Also ignores `no-useless-escape` rule because it doesn't behave with escaping characters in stringified regex patterns.
=> fix: fix ignore patterns

jest.config.js
This PR fixes the composition of addons with the `jest-config` plugin.
Items are passed in array, not in object.
=> fix: fixes jest-config composition

package-lock.json, package.json
Updated `@moxy/next-compile-node-modules` since it was causing a problem with different instances of React making stuff like React Hooks not working.
Check https://github.com/moxystudio/next-compile-node-modules/pull/4 for more information.
=> fix: use of react hooks

docusaurus/docs/what-is-included/available-scripts.md
This PR proposes a fix for a typo on the `Available Scripts` section. More precisely, the description for the `npm run lint:stylelint` was `This script lints only your JavaScript files` instead of `This script lints only your CSS files`.
=> fix: fix typo on available scripts section

docusaurus/docs/what-is-included/browser-support.md, docusaurus/sidebars.js, docusaurus/src/css/custom.css
Also:
- Lowercase "Browser Support" for consistency with other docs
- Let the header logo & title occupy the whole width when in tablet/mobile
=> docs: add link to private recipes

Dockerfile, docusaurus/docs/what-is-included/docker.md
- The intl package needs some OS deps
- The CMD now correctly starts the server on $PORT
=> fix: dockerfile deps and cmd

package.json
The "sideEffects" property in package.json improves webpack treeshaking. However that causes the out-of-order CSS we were seeing in production builds. We may enable again once the bug is fixed.
For more context see https://github.com/webpack/webpack/issues/7094 and https://github.com/webpack-contrib/mini-css-extract-plugin/issues/202.
=> fix: css out of order in a production build

.dockerignore, .env.sample, Dockerfile, README.md, docusaurus/docs/recipes/rest-api.md, docusaurus/docs/what-is-included/docker.md, docusaurus/docs/what-is-included/environment-variables.md, docusaurus/docs/what-is-included/eslint-stylelint.md, docusaurus/docs/what-is-included/webpack-file-loaders.md
- The final runtime image is much lighter because it doesn't contain dev dependencies and other intermediate artifacts produced during the build phase.
- It allows to target a specific stage when building, which is useful to create a CI/CD pipeline. As an example, you may run the project tests by specifying `--target check` when calling `docker build`.
=> chore: change dockerfile to support multi-stage builds

package.json
The current script posts always to the master branch, which is not always the case. As an example, you might be pushing to a release line branch containing a hotfix.
=> chore: push to current branch after a release

docusaurus/docs/welcome/conventions.md
Updated folder-structure in the conventions docs page by deleting `server.js` and adding the `package-lock.json` and `package.json` files.
=> docs: update folder-structure

www/shared/tests/utils/render-with-intl/render-with-intl.test.js
Fixes `rerenderWithIntl` test. Missed this during code review, so here's the PR with the fix.
As it was, this test was not testing whether `rerenderWithIntl` was wrapping the `intl` provider, because no child would require it.
With a `FormattedMessage` child, this test now actually tests if `rerenderWithIntl` wraps its children with the necessary provider and does not throw any errors.
=> fix: rerender with intl test

www/shared/styles/imports/custom-medias.css
⚠️ Merge after #46
custom-medias have now more breakpoints.
Besides, this is a new typology, since we are in 2020 and we don't know anymore what is the difference between a tablet and a phone width, I think that we need to be more agnostic.
What do you think about this?
see `www/shared/styles/imports/custom-medias.css`
=> refactor: custom medias to have more breakpoints

Dockerfile
This PR fixes the bug where files in `public` folder weren't being served when deploying with Docker.
=> fix: serve public assets with Docker

.env.sample, Dockerfile, docusaurus/docs/welcome/instructions.md, docusaurus/docs/what-is-included/docker.md, docusaurus/docs/what-is-included/environment-variables.md, next.config.js, package.json, www/app/App.data.js
Add SITE_URL environment variable to replace `{project-domain}` placeholder
Example application: https://frontend-mr1-4izymcemfa-ew.a.run.app/
Using the above URL in twitter and facebook card validators should show the default placeholder image and values
Twitter
---
Facebook
---
=> feat(ci): Fully qualified URL for SEO image

.eslintrc.json, docusaurus/docs/what-is-included/eslint-stylelint.md, package-lock.json, package.json
Given the recent refactoring of [MOXY's eslint-config](https://github.com/moxystudio/eslint-config), this PR switches the `eslint` configuration used from the previous deprecated one to the current version.
=> chore: update eslint config

.github/workflows/deploy-now.yml, .github/workflows/docker-ci.yml, .github/workflows/node-ci.yml, docusaurus/docs/what-is-included/environment-variables.md, next.config.js, package-lock.json, package.json
Implements validation to guarantee that `SITE_URL` is a valid URL. Currently, it only allows `http` for `localhost`, which might be too strict, so opinions welcome.
This implementation makes it so failure to validate will stop the app building process. 
This implementation also parallels the [`next-validation`](https://github.com/moxystudio/next-validation) package, which is made obsolete for this specific problem with this solution.
=> fix: validate SITE_URL env var as a valid URL

www/shared/styles/imports/mixins/typography.css
Right now `typography.css` isn't using custom medias accordingly to what we set in `custom-medias.css`.
This PR aims to fix this.
=> fix: typography target media

docusaurus/docs/recipes/dato-cms.md
This PR aims to fix an misleading code recipe that is not correct for the usage of CMS translations, since the query and the following code for intl are expecting an object of translations coming from CMS when it should be an array of objects containing keys and values.
=> fix: datocms translations recipe

docusaurus/static/recipes-assets/react-splash-screen/SplashScreen.test.js, www/app/App.test.js, www/pages/contacts/Contacts.test.js, www/pages/contacts/project-info/ProjectInfo.test.js, www/pages/error/ErrorPage.test.js, www/pages/home/Home.test.js, www/pages/terms/Terms.test.js, www/shared/modules/react-cookie-banner/CookieBanner.test.js, www/shared/modules/react-footer/Footer.test.js, www/shared/modules/react-header/Header.test.js, www/shared/modules/react-main-layout/MainLayout.test.js, www/shared/test-utils/index.js, www/shared/test-utils/modules/custom-queries/custom-queries.js, www/shared/test-utils/modules/custom-queries/index.js, www/shared/test-utils/modules/react-app-tree/AppTree.test.js
This PR will add a `customRender` function which is able to wrap a desired component into all the necessary providers (and anything else it needs). Note that this approach is recommended by the RTL's [documentation](https://testing-library.com/docs/react-testing-library/setup#custom-render).
I also took this opportunity to refactor some tests which were using the `container` property from a `render` instead of `screen` ([as suggested here](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen))
Motivation: https://github.com/moxystudio/react-native-with-moxy/pull/42#pullrequestreview-432694206
=> chore: add custom render

package-lock.json, package.json
`npm run dev` is throwing the following error:
When https://github.com/moxystudio/next-compile-node-modules/pull/10 was merged and released on v1.3.6, the dependency's version was not updated accordingly in the boilerplate. This PR fixes that.
CC @ruimonteiro93
=> Update next-compile-node-modules dependency

docusaurus/src/css/custom.css
This PR will fix the sidebar icon color for dark theme. It will white now, to help with the visibility.
=> fix: fix sidebar icon color for dark theme

.github/workflows/deploy-vercel.yml
The workflow which deploys to Vercel is currently failing:
The `set-env` command was [deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) a few months ago and recently disabled. This PR updates the workflow to use the [new syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files).
=> Use new syntax to set environment variables in CI
